### PR TITLE
Add open source contribution guide

### PR DESCRIPTION
**Pull request by semioticrobotic**
This PR adds a guide for contributing to SAS open source projects on GitHub. It outlines how to get started making contributions, where to find resources, how to comply with our agreements, and what to expect from SAS's open source project maintainers.

### CODE REVIEW

**Comment by semioticrobotic** [comment]
@suehle and @isharacomix: As discussed, here's an initial draft of a SAS contributors' guide. Please [take a look](https://github.com/sassoftware/sassoftware.github.io/blob/357874d52ece8c1590d2441b97fab8829cac1d37/contributor-guide.md) and let me know what you might change, add, etc.

Also flagging @cjdinger in case he has feedback to offer. And I'd be interested in @richmain-sas's impressions, too, but for some reason I'm unable to add him as a reviewer.

For context: this guide will be a sub-page of [https://sassoftware.github.io/](https://sassoftware.github.io/). It will be our "instructions of record" for open source contributors.

What I've committed so far is simply a Markdown file of draft text. When we're confident we've gotten the guide where we'd like it to be, I'll convert this document to HTML and re-circulate for additional review.

**Comment by semioticrobotic** [comment]
Thanks, @richmain-sas! I'll figure it out one of these days. 😏 Regardless, I really appreciate your review!

**Review by richmain-sas — APPROVED** [review]

**Comment by semioticrobotic** [comment]
@isharacomix, @suehle, @cjdinger: I've converted this to a basic HTML page for easier review, just so you can see what I'm driving at here. It's staged internally at SAS if you'd like to [see it in action](https://sww2.sas.com/~brbehr/contributor-guide.html).

As always, feedback welcome. Next I am working on connecting the primary landing page to the guide.

**Comment by semioticrobotic** [comment]
Okay! @isharacomix, @suehle, @cjdinger: After working through some internal feedback from @suehle, I think now have what I believe is a workable MVP of the new contributor handbook. This branch reflects all the changes, but I've also staged everything internally at SAS so you can see it in action.

1️⃣ [Refreshed home page](https://sww2.sas.com/~brbehr/) 
2️⃣ [The SAS Open Source Contributor Handbook](https://sww2.sas.com/~brbehr/contributor-handbook.html)

Please let me know what you think, especially if you have suggestions/requests for changes, ideas for improvements, etc. I'm all ears.

Operating on lazy consensus, if I don't hear objections to the new work in a day or two, I'll merge.

**Comment by semioticrobotic** [comment]
(Figured I would let @richmain-sas take a look at [the page layout](https://sww2.sas.com/~brbehr/contributor-handbook.html), too. 😎)

**Comment by cjdinger** [comment]
These changes are looking good @semioticrobotic! Just back from being away, and glad to see you didn't wait for my approval to proceed ;)

**Comment by semioticrobotic** [comment]
Great! Thanks, @cjdinger!

**Comment by semioticrobotic** [comment]
Also: welcome back!

**Pull request merged**
